### ISSUE TITLE
Userlist : non alphabetical order

### ISSUE THREAD

**Issue by pousterlus** [Libertempo/Libertempo-web#483]
* Prérequis : Having Libertempo installed up and running, with many users in it (installed_version  =  1.10).
* Action de déclenchement : See the userlist (admin or HR mode).
* Résultat attendu : Users listed by alphabetical order by "Name".
* Résultat constaté : Users listed but don't know which column...

Thanks.

-- 
Léo.

**Comment by pousterlus** [comment]
Hi Wouldsmina,

Meanwhile waiting for Mondaran version, is there a quick workaround to this bug in the code ?
I had a look but didn't find anything...

Thanks :)

-- 
Léo.

**Comment by wouldsmina** [comment]
Hi,

you must modify some SQL queries. I have not analyzed this problem yet, but you can try changing the `ORDER BY` condition:
- https://github.com/Libertempo/Libertempo-web/blob/develop/hr/Fonctions.php#L1259
- https://github.com/Libertempo/Libertempo-web/blob/develop/hr/Fonctions.php#L1203
- https://github.com/Libertempo/Libertempo-web/blob/develop/fonctions_conges.php#L943

a+

**Comment by Prytoegrian** [comment]
Done.

**Comment by pousterlus** [comment]
Hi Prytoegrian,

Sorry, but even after a git reset to the branch "develop", the bug is still there.
Names are not sorted alphabetically in the list.

-- 
Léo.

**Comment by Prytoegrian** [comment]
Indeed, I pushed the fix onto `beta` directly (`1.10` is about to be released). `develop` is our working branch, it's not recommended to use it in production.

Try to test `beta` and tell me if your bug disappears :smiley_cat:

**Comment by pousterlus** [comment]
Hello :)

I confirm that the bug no longer exists with the `beta `branch.
Can I use this beta branch in production ?

-- 
Léo.

**Comment by Prytoegrian** [comment]
`master` is a production branch, it can be used by any client at any time.
`beta` means « *we're about to merge this code onto `master` and release, but you may experience bugs* ». So, I can't answer for you. If you do, use it at your own risk.

Nevertheless, according to the criticality of your bug, I recommend patience. If all goes well, we will release `1.10` in few weeks ; with master, you're certain that all bugs are fixed.
